### ISSUE TITLE
Feedback on wiki 1

### ISSUE THREAD

**Issue by scharffc** [paceuniversity/CS3892016team3#1]
Your picture is missing.
VORD Section should be in Backlog section as preliminary work.
The list of tools should be already available. Same for communications.
The skeleton of the sprints should also be available!

@zerenato @arfhan786 @OrtegaChris

**Comment by scharffc** [comment]
@zerenato @arfhan786 @OrtegaChris

The wiki is still missing lots of required deliverables. Please update.

**Comment by zerenato** [comment]
Picture: Done
Move VORD into Backlog section: Done
Communication section: Done
Tools section: Done
Skeleton of the sprints: Done
